// ===================== SEED DATA =====================
// Skills enum: cambio (cambio di passo), controllo (controllo palla), dribbling, visione

const EXERCISES = [
  {id:"ex01", nome:"Tocchi rapidi in area 12x12", skill:"controllo", tipo:"ball mastery", livello:"base", durata:8,
    materiale:"1 pallone", video:"https://www.youtube.com/watch?v=-252rZPZuWA&t=15s",
    descrizione:"200-250 tocchi liberi alternando interno-interno, esterno-esterno, suola, dentro-fuori. Postura alta, testa libera."},
  {id:"ex02", nome:"Muro + controllo orientato", skill:"controllo", tipo:"muro", livello:"base", durata:12,
    materiale:"muro/rebounder, 1 pallone", video:"https://www.youtube.com/watch?v=SKx_c8jppEI",
    descrizione:"Passaggio al muro e controllo orientato a destra/sinistra dopo il rimbalzo. 4 serie da 2 minuti, alternando piede."},
  {id:"ex03", nome:"Slalom 6 coni + uscita forte", skill:"dribbling", tipo:"coni", livello:"medio", durata:15,
    materiale:"6 coni", video:"https://www.youtube.com/results?search_query=cone+slalom+dribbling+drill",
    descrizione:"Slalom tra 6 coni, uscita esplosiva di 5 metri dopo l'ultimo cono. 8 ripetizioni per lato, qualità prima della velocità."},
  {id:"ex04", nome:"Scansione colore prima del controllo", skill:"visione", tipo:"scansione", livello:"medio", durata:15,
    materiale:"2-3 cartoncini colorati, muro", video:"https://www.youtube.com/watch?v=YFnhW3hcuU8",
    descrizione:"Guarda il colore mostrato prima di ricevere dal muro: controllo orientato verso la porticina del colore visto."},
  {id:"ex05", nome:"Circuito continuo a tempo", skill:"controllo", tipo:"1v1 simulato", livello:"medio", durata:10,
    materiale:"coni, pallone", video:"https://www.youtube.com/shorts/J6U-YClb6AM",
    descrizione:"Circuito continuo: 45'' lavoro / 30'' pausa per 6 giri, combinando i gesti allenati nella seduta."},
  {id:"ex06", nome:"Ball mastery con suola (inside-outside)", skill:"controllo", tipo:"ball mastery", livello:"base", durata:8,
    materiale:"1 pallone", video:"https://www.youtube.com/results?search_query=sole+rolls+inside+outside+drill",
    descrizione:"Inside-outside e pull-push con la suola, ritmo costante, alternando piede dominante e debole."},
  {id:"ex07", nome:"Quadrato 5x5: controllo e uscita", skill:"controllo", tipo:"coni", livello:"medio", durata:12,
    materiale:"4 coni", video:"https://www.youtube.com/results?search_query=5x5+square+ball+control+drill",
    descrizione:"Controllo in un angolo del quadrato, uscita verso un altro lato con massimo 3 tocchi."},
  {id:"ex08", nome:"Guida palla in corridoio stretto", skill:"dribbling", tipo:"coni", livello:"medio", durata:15,
    materiale:"8 coni (4 corsie da 8m)", video:"https://www.youtube.com/results?search_query=narrow+corridor+dribbling+drill",
    descrizione:"Dribbling in 4 corsie stretta da 8m, obiettivo: non toccare i coni, alternando velocità."},
  {id:"ex09", nome:"Challenge tecnica a serie", skill:"controllo", tipo:"1v1 simulato", livello:"medio", durata:10,
    materiale:"pallone, coni", video:"https://www.youtube.com/results?search_query=technical+challenge+clean+executions",
    descrizione:"Conta quante esecuzioni pulite riesci a fare in 10 serie del gesto allenato oggi."},
  {id:"ex10", nome:"Tocchi alternati interno-esterno", skill:"controllo", tipo:"ball mastery", livello:"base", durata:8,
    materiale:"1 pallone", video:"https://www.youtube.com/results?search_query=inside+outside+touches+both+feet",
    descrizione:"Tocchi alternati interno-esterno con piede dominante e debole, rapporto 60/40 verso il piede debole."},
  {id:"ex11", nome:"Ricezione suola + uscita interno", skill:"controllo", tipo:"muro", livello:"medio", durata:12,
    materiale:"muro, pallone", video:"https://www.youtube.com/results?search_query=sole+receive+inside+foot+exit",
    descrizione:"Ricezione con interno, uscita con esterno; poi ricezione con suola, uscita con interno. Alterna lati."},
  {id:"ex12", nome:"Finta sul cono + cambio di passo", skill:"cambio", tipo:"coni", livello:"medio", durata:15,
    materiale:"1 cono centrale", video:"https://www.youtube.com/results?search_query=fake+and+go+cone+acceleration",
    descrizione:"Attacco frontale al cono, finta di corpo e uscita in diagonale con cambio di passo deciso."},
  {id:"ex13", nome:"Check spalla + controllo aperto", skill:"visione", tipo:"muro", livello:"medio", durata:15,
    materiale:"muro, mini porta", video:"https://www.youtube.com/results?search_query=check+shoulder+open+control+pass",
    descrizione:"Passaggio al muro, check spalla prima di ricevere, controllo aperto e passaggio rapido in mini porta."},
  {id:"ex14", nome:"Combinazione tecnica libera", skill:"dribbling", tipo:"1v1 simulato", livello:"medio", durata:10,
    materiale:"pallone, coni", video:"https://www.youtube.com/results?search_query=freestyle+technical+combo+football",
    descrizione:"Combinazione libera dei 3 gesti tecnici preferiti, ricerca della fluidità e velocità di esecuzione."},
  {id:"ex15", nome:"Sequenze veloci/controllo 20-20-20", skill:"cambio", tipo:"ball mastery", livello:"medio", durata:8,
    materiale:"pallone", video:"https://www.youtube.com/results?search_query=20+seconds+fast+touches+control+drill",
    descrizione:"20'' tocchi veloci + 20'' controllo lento + 20'' veloci. Lavora sul cambio di ritmo dentro lo stesso esercizio."},
  {id:"ex16", nome:"Controllo a seguire su passaggio", skill:"controllo", tipo:"muro", livello:"medio", durata:12,
    materiale:"muro/partner, pallone", video:"https://www.youtube.com/results?search_query=running+control+rolling+pass",
    descrizione:"Controllo a seguire su passaggio rasoterra e mezza altezza, mantenendo corsa fluida."},
  {id:"ex17", nome:"Zig-zag 8 coni + sprint finale", skill:"cambio", tipo:"coni", livello:"difficile", durata:15,
    materiale:"8 coni", video:"https://www.youtube.com/results?search_query=zigzag+cones+sprint+finish+dribbling",
    descrizione:"Zig-zag tra 8 coni, ultimi 3 metri in massima velocità con palla al piede."},
  {id:"ex18", nome:"Stimolo visivo 2 colori (giro/taglio)", skill:"visione", tipo:"scansione", livello:"difficile", durata:15,
    materiale:"2 cartoncini colorati", video:"https://www.youtube.com/results?search_query=color+cue+decision+drill+football",
    descrizione:"Rosso = giro esterno, giallo = taglio interno. Il segnale arriva mentre conduci, decisione rapida."},
  {id:"ex19", nome:"Test 1 minuto slalom pulito", skill:"dribbling", tipo:"coni", livello:"difficile", durata:10,
    materiale:"6 coni, cronometro", video:"https://www.youtube.com/results?search_query=1+minute+slalom+test+football",
    descrizione:"Test: 3 tentativi di slalom pulito in 1 minuto, conta i passaggi senza toccare i coni."},
  {id:"ex20", nome:"Tocchi rapidi in box 4x4", skill:"controllo", tipo:"ball mastery", livello:"base", durata:8,
    materiale:"4 coni", video:"https://www.youtube.com/results?search_query=4x4+box+touches+drill",
    descrizione:"Tocchi rapidi all'interno di un box ridotto 4x4, alta frequenza, controllo dello spazio personale."},
  {id:"ex21", nome:"Controllo orientato sotto pressione immaginaria", skill:"controllo", tipo:"1v1 simulato", livello:"medio", durata:12,
    materiale:"pallone, cono", video:"https://www.youtube.com/results?search_query=oriented+first+touch+under+pressure",
    descrizione:"Controllo orientato con un tocco, simulando la presenza di un avversario dietro la schiena."},
  {id:"ex22", nome:"4 cancelli numerati + finta in uscita", skill:"visione", tipo:"porticine", livello:"difficile", durata:15,
    materiale:"4 coppie di coni numerate", video:"https://www.youtube.com/results?search_query=numbered+gates+dribbling+decision",
    descrizione:"Si parte dal centro, viene chiamato un numero e si attacca il cancello corrispondente con finta in uscita."},
  {id:"ex23", nome:"Scan & decide con 2 porticine", skill:"visione", tipo:"porticine", livello:"difficile", durata:15,
    materiale:"4 coni (2 porticine)", video:"https://www.youtube.com/results?search_query=scan+and+decide+two+gates+drill",
    descrizione:"Scansione prima della ricezione, poi scelta tra passaggio di prima o conduzione breve verso una porticina."},
  {id:"ex24", nome:"Circuito 3 stazioni", skill:"controllo", tipo:"1v1 simulato", livello:"medio", durata:10,
    materiale:"coni, muro, pallone", video:"https://www.youtube.com/results?search_query=3+station+technical+circuit+football",
    descrizione:"Circuito a 3 stazioni (controllo, dribbling, visione) da ripetere 3 volte con qualità costante."},
  {id:"ex25", nome:"Revisione: i 4 esercizi migliori", skill:"dribbling", tipo:"1v1 simulato", livello:"medio", durata:12,
    materiale:"vario", video:"https://www.youtube.com/results?search_query=football+technical+review+best+drills",
    descrizione:"Ripeti i 4 esercizi che ti sono piaciuti/riusciti meglio questa settimana, 12 minuti ciascuno."},
  {id:"ex26", nome:"Test controllo orientato (su 20)", skill:"controllo", tipo:"1v1 simulato", livello:"difficile", durata:12,
    materiale:"muro, pallone", video:"https://www.youtube.com/results?search_query=oriented+control+test+20+reps",
    descrizione:"Test: numero di controlli orientati riusciti su 20 tentativi dal muro."},
  {id:"ex27", nome:"Test scelta corretta su segnali (su 12)", skill:"visione", tipo:"scansione", livello:"difficile", durata:12,
    materiale:"cartoncini/coni colorati", video:"https://www.youtube.com/results?search_query=visual+cue+decision+test+football",
    descrizione:"Test: numero di scelte corrette su 12 segnali visivi mostrati durante la conduzione."},
  {id:"ex28", nome:"Recupero tecnico: juggling libero", skill:"controllo", tipo:"ball mastery", livello:"base", durata:15,
    materiale:"pallone", video:"https://www.youtube.com/results?search_query=juggling+freestyle+recovery+session",
    descrizione:"Juggling libero e tocchi creativi a bassa intensità, focus sul piacere del tocco di palla."},
  {id:"ex29", nome:"Tocchi liberi piede debole", skill:"controllo", tipo:"ball mastery", livello:"base", durata:15,
    materiale:"pallone", video:"https://www.youtube.com/results?search_query=weak+foot+touches+recovery",
    descrizione:"Sessione leggera dedicata interamente al piede debole: tocchi, controlli, piccoli passaggi al muro."},
  {id:"ex30", nome:"Finta forbice + uscita esplosiva", skill:"cambio", tipo:"coni", livello:"medio", durata:15,
    materiale:"1-2 coni", video:"https://www.youtube.com/results?search_query=scissor+feint+explosive+exit",
    descrizione:"Finta forbice (o doppio passo) davanti al cono, seguita da uscita esplosiva di 5 metri."},
  {id:"ex31", nome:"Slalom asimmetrico", skill:"dribbling", tipo:"coni", livello:"difficile", durata:15,
    materiale:"6 coni a distanze variabili", video:"https://www.youtube.com/results?search_query=asymmetric+cone+slalom+drill",
    descrizione:"Slalom con distanze diverse tra i coni: obbliga ad adattare la frequenza del tocco in tempo reale."},
  {id:"ex32", nome:"Ricezione con vincolo primo tocco fuori", skill:"visione", tipo:"muro", livello:"difficile", durata:15,
    materiale:"muro, pallone", video:"https://www.youtube.com/results?search_query=first+touch+away+from+pressure+drill",
    descrizione:"Ricezione dal muro con vincolo: il primo tocco deve portare la palla lontano da un 'difensore' immaginario."},
  {id:"ex33", nome:"Cambio di passo dopo doppio controllo", skill:"cambio", tipo:"1v1 simulato", livello:"difficile", durata:12,
    materiale:"pallone, coni", video:"https://www.youtube.com/results?search_query=double+touch+acceleration+drill",
    descrizione:"Doppio controllo orientato seguito immediatamente da accelerazione di 5-8 metri in direzione diversa."},
  {id:"ex34", nome:"1v1 tecnico contro sagoma/cone gate", skill:"dribbling", tipo:"1v1 simulato", livello:"difficile", durata:10,
    materiale:"sagoma o 2 coni a porta", video:"https://www.youtube.com/results?search_query=1v1+technical+vs+cone+gate",
    descrizione:"1v1 simulato contro sagoma o cone gate, obiettivo esecuzione pulita del gesto tecnico scelto."},
  {id:"ex35", nome:"Densità: circuito completo cronometrato", skill:"controllo", tipo:"1v1 simulato", livello:"difficile", durata:15,
    materiale:"tutto il materiale disponibile", video:"https://www.youtube.com/results?search_query=full+technical+circuit+timed+test",
    descrizione:"Circuito completo che unisce controllo, dribbling, cambio di passo e visione, cronometrato, pause minime."}
];

// helper to build a session block reference
function blk(exId, note){ return {exId, note: note||""}; }

// Build 4 weeks x 7 days program. Each day = {title, focus, durata, livello, blocks:[...]}
const PROGRAM_SEED = {
  1: [
    {title:"Dominio palla e primo controllo", focus:"controllo", livello:"base", durata:60,
     blocks:[blk("ex01"), blk("ex02"), blk("ex03"), blk("ex04"), blk("ex05")]},
    {title:"Conduzione stretta", focus:"dribbling", livello:"base", durata:60,
     blocks:[blk("ex06"), blk("ex07"), blk("ex08"), blk("ex04","variante: guida verso il colore"), blk("ex09")]},
    {title:"Interno/esterno e sterzata", focus:"controllo", livello:"medio", durata:60,
     blocks:[blk("ex10"), blk("ex11"), blk("ex12"), blk("ex13"), blk("ex14")]},
    {title:"Ritmo e coordinazione tecnica", focus:"cambio", livello:"medio", durata:60,
     blocks:[blk("ex15"), blk("ex16"), blk("ex17"), blk("ex18"), blk("ex19")]},
    {title:"Tecnica in spazi ridotti", focus:"visione", livello:"medio", durata:60,
     blocks:[blk("ex20"), blk("ex21"), blk("ex22"), blk("ex23"), blk("ex24")]},
    {title:"Revisione settimana 1", focus:"controllo", livello:"medio", durata:60,
     blocks:[blk("ex25"), blk("ex26"), blk("ex27")]},
    {title:"Recupero tecnico attivo", focus:"controllo", livello:"facile", durata:60,
     blocks:[blk("ex28"), blk("ex29"), blk("ex02","ritmo basso")]}
  ],
  2: [
    {title:"Dribbling lineare + sprint", focus:"cambio", livello:"medio", durata:60,
     blocks:[blk("ex08"), blk("ex02"), blk("ex04"), blk("ex17"), blk("ex05")]},
    {title:"Finta forbice ed esplosività", focus:"cambio", livello:"medio", durata:60,
     blocks:[blk("ex01"), blk("ex30"), blk("ex12"), blk("ex18"), blk("ex09")]},
    {title:"Slalom asimmetrico", focus:"dribbling", livello:"difficile", durata:60,
     blocks:[blk("ex06"), blk("ex31"), blk("ex11"), blk("ex23"), blk("ex24")]},
    {title:"Ricezione fuori pressione", focus:"visione", livello:"difficile", durata:60,
     blocks:[blk("ex10"), blk("ex32"), blk("ex12"), blk("ex22"), blk("ex19")]},
    {title:"Doppio controllo e accelerazione", focus:"cambio", livello:"difficile", durata:60,
     blocks:[blk("ex20"), blk("ex33"), blk("ex17"), blk("ex18"), blk("ex05")]},
    {title:"Revisione settimana 2", focus:"cambio", livello:"medio", durata:60,
     blocks:[blk("ex25"), blk("ex19"), blk("ex27")]},
    {title:"Recupero tecnico attivo", focus:"controllo", livello:"facile", durata:60,
     blocks:[blk("ex28"), blk("ex29"), blk("ex06")]}
  ],
  3: [
    {title:"Lettura segnali e prima scelta", focus:"visione", livello:"medio", durata:60,
     blocks:[blk("ex01"), blk("ex04"), blk("ex23"), blk("ex22"), blk("ex24")]},
    {title:"Scan prima e dopo il controllo", focus:"visione", livello:"medio", durata:60,
     blocks:[blk("ex10"), blk("ex13"), blk("ex32"), blk("ex18"), blk("ex09")]},
    {title:"Decisione sotto pressione di tempo", focus:"visione", livello:"difficile", durata:60,
     blocks:[blk("ex20"), blk("ex21"), blk("ex22"), blk("ex27"), blk("ex05")]},
    {title:"Cambio di passo su stimolo", focus:"cambio", livello:"difficile", durata:60,
     blocks:[blk("ex15"), blk("ex33"), blk("ex17"), blk("ex18"), blk("ex19")]},
    {title:"Dribbling decisionale", focus:"dribbling", livello:"difficile", durata:60,
     blocks:[blk("ex06"), blk("ex31"), blk("ex34"), blk("ex23"), blk("ex24")]},
    {title:"Revisione settimana 3", focus:"visione", livello:"medio", durata:60,
     blocks:[blk("ex25"), blk("ex27"), blk("ex19")]},
    {title:"Recupero tecnico attivo", focus:"controllo", livello:"facile", durata:60,
     blocks:[blk("ex28"), blk("ex29"), blk("ex02")]}
  ],
  4: [
    {title:"Consolidamento controllo", focus:"controllo", livello:"difficile", durata:60,
     blocks:[blk("ex01"), blk("ex26"), blk("ex11"), blk("ex32"), blk("ex35")]},
    {title:"Consolidamento cambio di passo", focus:"cambio", livello:"difficile", durata:60,
     blocks:[blk("ex15"), blk("ex33"), blk("ex17"), blk("ex30"), blk("ex35")]},
    {title:"Consolidamento dribbling", focus:"dribbling", livello:"difficile", durata:60,
     blocks:[blk("ex06"), blk("ex31"), blk("ex34"), blk("ex08"), blk("ex35")]},
    {title:"Consolidamento visione di gioco", focus:"visione", livello:"difficile", durata:60,
     blocks:[blk("ex04"), blk("ex23"), blk("ex22"), blk("ex27"), blk("ex35")]},
    {title:"Densità: circuito completo", focus:"controllo", livello:"difficile", durata:60,
     blocks:[blk("ex20"), blk("ex24"), blk("ex35"), blk("ex19"), blk("ex09")]},
    {title:"Test finale del mese", focus:"controllo", livello:"difficile", durata:60,
     blocks:[blk("ex19"), blk("ex26"), blk("ex27"), blk("ex35")]},
    {title:"Recupero e bilancio finale", focus:"controllo", livello:"facile", durata:60,
     blocks:[blk("ex28"), blk("ex29"), blk("ex25")]}
  ]
};

const PLAYER_SEED = {
  nome: "Marco",
  eta: 16,
  ruolo: "Esterno offensivo",
  skills: { cambio: 55, controllo: 60, dribbling: 58, visione: 50 },
  xp: 0,
  livello: 1,
  streak: 0,
  badges: [],
  noteUtente: ""
};

const SKILL_LABELS = {
  cambio: "Cambio di passo",
  controllo: "Controllo palla",
  dribbling: "Dribbling",
  visione: "Visione di gioco"
};

const LIVELLO_LABELS = { base:"Base", facile:"Facile", medio:"Medio", difficile:"Difficile" };
